import type { Product, Review, Coupon } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Velvet Matte Lipstick',
    brand: 'Glamour',
    category: 'Lips',
    price: 24.99,
    originalPrice: 29.99,
    emoji: '💄',
    description:
      'A richly pigmented, long-lasting matte lipstick that glides on smoothly and keeps your lips vibrant all day. Infused with vitamin E for a touch of care.',
    rating: 4.8,
    reviewCount: 412,
    shades: [
      { name: 'Ruby Red', hex: '#c0392b', stock: 50 },
      { name: 'Berry Bliss', hex: '#8e44ad', stock: 30 },
      { name: 'Nude Glow', hex: '#d4a574', stock: 45 },
    ],
    badge: 'SALE',
    isNew: false,
    isSubscriptionEligible: true,
  },
  {
    id: '2',
    name: 'Hydrating Serum',
    brand: 'GlowLab',
    category: 'Skincare',
    price: 49.99,
    emoji: '🧴',
    description:
      'A lightweight, fast-absorbing serum packed with hyaluronic acid and niacinamide to hydrate, plump, and brighten your complexion.',
    rating: 4.9,
    reviewCount: 289,
    shades: [],
    badge: 'HOT',
    isNew: false,
    isSubscriptionEligible: true,
  },
  {
    id: '3',
    name: 'Midnight Bloom Eau de Parfum',
    brand: 'Maison Luxe',
    category: 'Perfume',
    price: 89.99,
    originalPrice: 110.0,
    emoji: '🌸',
    description:
      'An enchanting floral fragrance with notes of jasmine, tuberose, and vanilla. Perfect for evening elegance and special occasions.',
    rating: 4.7,
    reviewCount: 156,
    shades: [],
    badge: 'SALE',
    isNew: false,
  },
  {
    id: '4',
    name: 'Precision Liquid Eyeliner',
    brand: 'Glamour',
    category: 'Eyes',
    price: 16.99,
    emoji: '👁',
    description:
      'A smudge-proof, intensely black liquid eyeliner with a precision tip for flawless wing application every time. Lasts up to 16 hours.',
    rating: 4.5,
    reviewCount: 523,
    shades: [],
    badge: null,
    isNew: false,
  },
  {
    id: '5',
    name: 'Dewy Finish Foundation',
    brand: 'GlowLab',
    category: 'Face',
    price: 39.99,
    originalPrice: 44.99,
    emoji: '✨',
    description:
      'A buildable, medium-coverage foundation with a luminous dewy finish. Enriched with SPF 30 and squalane for a healthy glow.',
    rating: 4.6,
    reviewCount: 378,
    shades: [
      { name: 'Ivory', hex: '#f5e6d3', stock: 40 },
      { name: 'Sand', hex: '#d4a574', stock: 35 },
      { name: 'Tan', hex: '#a0714f', stock: 25 },
      { name: 'Espresso', hex: '#5c3a21', stock: 20 },
    ],
    badge: null,
    isNew: false,
    isSubscriptionEligible: true,
  },
  {
    id: '6',
    name: 'Overnight Retinol Cream',
    brand: 'DermPure',
    category: 'Skincare',
    price: 59.99,
    emoji: '🌙',
    description:
      'A powerful yet gentle night cream with encapsulated retinol and ceramides to reduce fine lines and improve skin texture while you sleep.',
    rating: 4.7,
    reviewCount: 201,
    shades: [],
    badge: 'NEW',
    isNew: true,
    isSubscriptionEligible: true,
  },
  {
    id: '7',
    name: 'Shimmer Highlighting Palette',
    brand: 'Glamour',
    category: 'Face',
    price: 32.99,
    emoji: '✨',
    description:
      'A curated palette of three buildable highlighters — champagne, rose gold, and bronze — for a lit-from-within glow on any skin tone.',
    rating: 4.4,
    reviewCount: 167,
    shades: [
      { name: 'Champagne', hex: '#f7e7ce', stock: 30 },
      { name: 'Rose Gold', hex: '#e8a8a0', stock: 25 },
      { name: 'Bronze', hex: '#c48a5c', stock: 20 },
    ],
    badge: null,
    isNew: false,
  },
  {
    id: '8',
    name: 'Rose Petal Lip Balm',
    brand: 'Botanic',
    category: 'Lips',
    price: 12.99,
    emoji: '💄',
    description:
      'A nourishing, tinted lip balm infused with rosehip oil and shea butter. Keeps lips soft, hydrated, and delicately pink.',
    rating: 4.3,
    reviewCount: 94,
    shades: [
      { name: 'Clear Pink', hex: '#f2b5c4', stock: 60 },
      { name: 'Blush', hex: '#e896a8', stock: 45 },
    ],
    badge: null,
    isNew: true,
  },
  {
    id: '9',
    name: 'Volumizing Mascara',
    brand: 'Glamour',
    category: 'Eyes',
    price: 22.99,
    emoji: '👁',
    description:
      'A dramatic volumizing mascara with a curved brush that lifts, separates, and coats every lash for a wide-eyed, fanned-out look.',
    rating: 4.6,
    reviewCount: 634,
    shades: [],
    badge: 'HOT',
    isNew: false,
  },
  {
    id: '10',
    name: 'Citrus Burst Body Lotion',
    brand: 'Botanic',
    category: 'Skincare',
    price: 18.99,
    emoji: '🧴',
    description:
      'A zesty, fast-absorbing body lotion with grapefruit and bergamot. Leaves skin silky-smooth with a refreshing citrus scent.',
    rating: 4.2,
    reviewCount: 78,
    shades: [],
    badge: null,
    isNew: false,
  },
  {
    id: '11',
    name: 'Velvet Lip Gloss',
    brand: 'Glamour',
    category: 'Lips',
    price: 18.99,
    originalPrice: 22.99,
    emoji: '💄',
    description:
      'A high-shine, non-sticky lip gloss with a velvet applicator. Infused with jojoba oil for a plump, hydrated pout.',
    rating: 4.4,
    reviewCount: 203,
    shades: [
      { name: 'Petal Pink', hex: '#e8a0b0', stock: 35 },
      { name: 'Coral Pop', hex: '#e87050', stock: 28 },
    ],
    badge: 'SALE',
    isNew: false,
  },
  {
    id: '12',
    name: 'Gentle Micellar Water',
    brand: 'DermPure',
    category: 'Skincare',
    price: 14.99,
    emoji: '🧴',
    description:
      'A soothing, no-rinse micellar water that removes makeup and impurities without stripping the skin. Suitable for sensitive eyes.',
    rating: 4.8,
    reviewCount: 445,
    shades: [],
    badge: null,
    isNew: false,
  },
  {
    id: '13',
    name: 'Island Breeze Perfume',
    brand: 'Maison Luxe',
    category: 'Perfume',
    price: 72.0,
    originalPrice: 90.0,
    emoji: '🌸',
    description:
      'A vibrant, tropical fragrance blending coconut water, hibiscus, and sea salt. Transports you to a sun-soaked island escape.',
    rating: 4.5,
    reviewCount: 112,
    shades: [],
    badge: 'SALE',
    isNew: false,
  },
  {
    id: '14',
    name: 'Matte Bronzer Powder',
    brand: 'Glamour',
    category: 'Face',
    price: 28.99,
    emoji: '✨',
    description:
      'A silky, blendable bronzer in a warm neutral tone. Gives your complexion a natural, sun-kissed warmth without shimmer.',
    rating: 4.3,
    reviewCount: 198,
    shades: [],
    badge: null,
    isNew: false,
  },
  {
    id: '15',
    name: '24h Stay Eyeliner Pencil',
    brand: 'Glamour',
    category: 'Eyes',
    price: 14.99,
    emoji: '👁',
    description:
      'A waterproof, ultra-soft eyeliner pencil that delivers intense color in one swipe. Never needs sharpening — twist-up design.',
    rating: 4.1,
    reviewCount: 87,
    shades: [
      { name: 'Black', hex: '#1a1a1a', stock: 50 },
      { name: 'Brown', hex: '#6b4423', stock: 30 },
    ],
    badge: null,
    isNew: true,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    reviewerName: 'Sophia M.',
    isVerified: true,
    date: '2026-05-28',
    rating: 5,
    body: 'Absolutely love this lipstick! The color is rich and lasts through lunch without fading. The velvet finish is stunning.',
    helpful: 24,
    notHelpful: 1,
  },
  {
    id: 'r2',
    productId: '1',
    reviewerName: 'Emma L.',
    isVerified: true,
    date: '2026-05-25',
    rating: 5,
    body: 'My new go-to red. The shade Ruby Red is perfect for my skin tone. Feels moisturizing for a matte lipstick.',
    helpful: 18,
    notHelpful: 0,
  },
  {
    id: 'r3',
    productId: '1',
    reviewerName: 'Olivia K.',
    isVerified: false,
    date: '2026-05-20',
    rating: 4,
    body: 'Great formula but the nude shade ran a bit lighter than expected. Still a beautiful lipstick though!',
    helpful: 7,
    notHelpful: 2,
  },
  {
    id: 'r4',
    productId: '2',
    reviewerName: 'Mia T.',
    isVerified: true,
    date: '2026-05-22',
    rating: 5,
    body: 'My skin has never looked better! The serum absorbs instantly and my fine lines are visibly reduced after two weeks.',
    helpful: 32,
    notHelpful: 0,
  },
  {
    id: 'r5',
    productId: '2',
    reviewerName: 'Isabella R.',
    isVerified: true,
    date: '2026-05-18',
    rating: 5,
    body: 'Worth every penny. Lightweight and hydrating without being sticky. I use it morning and night.',
    helpful: 21,
    notHelpful: 1,
  },
  {
    id: 'r6',
    productId: '9',
    reviewerName: 'Ava W.',
    isVerified: true,
    date: '2026-05-26',
    rating: 5,
    body: "Best mascara I've ever used! No clumps, amazing volume, and stays put all day without smudging.",
    helpful: 45,
    notHelpful: 2,
  },
  {
    id: 'r7',
    productId: '9',
    reviewerName: 'Charlotte D.',
    isVerified: true,
    date: '2026-05-15',
    rating: 4,
    body: "Really great mascara. Gives nice volume and length. Only minor issue is it's a bit tricky to remove.",
    helpful: 13,
    notHelpful: 1,
  },
  {
    id: 'r8',
    productId: '12',
    reviewerName: 'Amelia J.',
    isVerified: true,
    date: '2026-05-24',
    rating: 5,
    body: "Finally found a micellar water that doesn't sting my eyes! Takes off even waterproof makeup effortlessly.",
    helpful: 28,
    notHelpful: 0,
  },
  {
    id: 'r9',
    productId: '12',
    reviewerName: 'Harper B.',
    isVerified: true,
    date: '2026-05-19',
    rating: 5,
    body: 'Gentle and effective. My sensitive skin loves this. No breakouts and no irritation. Highly recommend!',
    helpful: 19,
    notHelpful: 1,
  },
  {
    id: 'r10',
    productId: '6',
    reviewerName: 'Ella N.',
    isVerified: true,
    date: '2026-05-27',
    rating: 5,
    body: "I've been using this retinol cream for a month and the difference is remarkable. My skin is smoother and brighter.",
    helpful: 36,
    notHelpful: 0,
  },
  {
    id: 'r11',
    productId: '6',
    reviewerName: 'Scarlett G.',
    isVerified: true,
    date: '2026-05-21',
    rating: 4,
    body: "Very effective but start slow — my skin needed a week to adjust. Now it's part of my nightly routine.",
    helpful: 15,
    notHelpful: 1,
  },
  {
    id: 'r12',
    productId: '3',
    reviewerName: 'Victoria H.',
    isVerified: true,
    date: '2026-05-23',
    rating: 5,
    body: 'This perfume is absolutely divine! Lasts all day and I get compliments everywhere I go. The jasmine note is heavenly.',
    helpful: 27,
    notHelpful: 1,
  },
];

export const coupons: Coupon[] = [
  { code: 'GLAM20', discountPercent: 20, isActive: true },
  { code: 'BEAUTY10', discountPercent: 10, isActive: true },
  { code: 'EXPIRED50', discountPercent: 50, isActive: false },
];
